# traductions.py

def get_traductions():
    return {
        "fr": {
            "accueil_titre": "💧 Water Quality App",
            "accueil_soustitre": "Plateforme intelligente pour l’analyse de la qualité de l’eau potable en Algérie",
            "entrer": "➡️ Entrer dans le menu principal",
            "menu_principal": "Menu principal",
            "base_donnees": "📋 Base de données",
            "prediction": "🔍 Prédiction",
            "classification": "🧠 Classification",
            "pollution": "☣️ Détection Pollution",
            "visualisation": "📊 Visualisation",
            "assistant": "💬 Assistant IA",
            "retour": "🔚 Retour à l’accueil",
            "version": "Version 1.0 – Propulsée par la science, l’innovation et la passion pour l’environnement 💙",
            "selection_duree": "⏳ Sélectionnez la durée à afficher :",
            "param_evolution": "Évolution de",
            "distribution": "Distribution de",
            "comparaison_norme": "📉 Comparaison avec la norme",
            "aucune_donnee": "⚠️ Aucune donnée enregistrée.",
            "telecharger_pdf": "📄 Télécharger le rapport PDF",
            "telecharger_excel": "📥 Télécharger en Excel",
        },
        "en": {
            "accueil_titre": "💧 Water Quality App",
            "accueil_soustitre": "Smart platform for drinking water quality analysis in Algeria",
            "entrer": "➡️ Enter the main menu",
            "menu_principal": "Main Menu",
            "base_donnees": "📋 Database",
            "prediction": "🔍 Prediction",
            "classification": "🧠 Classification",
            "pollution": "☣️ Pollution Detection",
            "visualisation": "📊 Visualization",
            "assistant": "💬 AI Assistant",
            "retour": "🔚 Back to Home",
            "version": "Version 1.0 – Powered by science, innovation and environmental passion 💙",
            "selection_duree": "⏳ Select duration to display:",
            "param_evolution": "Evolution of",
            "distribution": "Distribution of",
            "comparaison_norme": "📉 Comparison with the standard",
            "aucune_donnee": "⚠️ No data recorded.",
            "telecharger_pdf": "📄 Download PDF Report",
            "telecharger_excel": "📥 Download as Excel",
        },
        "es": {
            "accueil_titre": "💧 Aplicación de Calidad del Agua",
            "accueil_soustitre": "Plataforma inteligente para el análisis de la calidad del agua potable en Argelia",
            "entrer": "➡️ Entrar al menú principal",
            "menu_principal": "Menú Principal",
            "base_donnees": "📋 Base de datos",
            "prediction": "🔍 Predicción",
            "classification": "🧠 Clasificación",
            "pollution": "☣️ Detección de contaminación",
            "visualisation": "📊 Visualización",
            "assistant": "💬 Asistente IA",
            "retour": "🔚 Volver al inicio",
            "version": "Versión 1.0 – Impulsada por la ciencia, la innovación y la pasión por el medio ambiente 💙",
            "selection_duree": "⏳ Seleccione la duración a mostrar:",
            "param_evolution": "Evolución de",
            "distribution": "Distribución de",
            "comparaison_norme": "📉 Comparación con la norma",
            "aucune_donnee": "⚠️ No hay datos registrados.",
            "telecharger_pdf": "📄 Descargar informe PDF",
            "telecharger_excel": "📥 Descargar en Excel",
        },
        "ar": {
            "accueil_titre": "💧 تطبيق جودة المياه",
            "accueil_soustitre": "منصة ذكية لتحليل جودة مياه الشرب في الجزائر",
            "entrer": "➡️ الدخول إلى القائمة الرئيسية",
            "menu_principal": "القائمة الرئيسية",
            "base_donnees": "📋 قاعدة البيانات",
            "prediction": "🔍 التنبؤ",
            "classification": "🧠 التصنيف",
            "pollution": "☣️ كشف التلوث",
            "visualisation": "📊 التصور البياني",
            "assistant": "💬 المساعد الذكي",
            "retour": "🔚 العودة إلى الصفحة الرئيسية",
            "version": "الإصدار 1.0 – مدفوع بالعلم والابتكار والشغف بالبيئة 💙",
            "selection_duree": "⏳ اختر المدة الزمنية للعرض:",
            "param_evolution": "تطور",
            "distribution": "توزيع",
            "comparaison_norme": "📉 المقارنة مع المعيار",
            "aucune_donnee": "⚠️ لا توجد بيانات مسجلة.",
            "telecharger_pdf": "📄 تحميل تقرير PDF",
            "telecharger_excel": "📥 تحميل كـ Excel",
        }
    }
